# run: conda update conda
# run: conda update --all
# run: conda env create --file environment.yml
# run: source activate template
name: template
dependencies:
  - python
  - matplotlib
  - jupyterlab
  - scikit-learn
  - scipy
  - pathlib
  - pandas
  - requests
  - python-dotenv
  - qgrid
  - seaborn
  - pip
  - pip:
    - -e .
